### ISSUE TITLE
Team12 Review: Land FRs

### ISSUE THREAD

**Issue by YoussefRizkalla** [brandonduong/Farming-Matters#13]
FR10 specifies that users are able to buy land and some other FRs are restrained to the user's owned land as a form of progression. However, there is no requirement which specifies if there is a limit on the land's size, price, crop availability, how many crops can grow on it, if it can be expanded, etc. which one might view as an essential part of a farming game. Furthermore, it is not specified if the user can own only one piece of land or multiple ones, or if they can be expanded at some point.

CC: @CSchank

**Comment by AndrewBal802** [comment]
Addressed!
