### ISSUE TITLE
Team12 Review: No requirement for access models

### ISSUE THREAD

**Issue by dipesube** [brandonduong/Farming-Matters#16]
There are no requirements for access models, which leaves vulnerabilities for security. It is unclear who can access what type of data. Users create accounts with a username and password, but can admins access this data? In the instance of cheating or hacking, are admins able to access the user data to deal with cheaters? Access to the logging data is also unclear. Is it only accessible to the professor and the developers or users as well? Also, will users be notified of their data being accessed?

CC: @CSchank

**Comment by AndrewBal802** [comment]
Addressed!
