### ISSUE TITLE
Team 32 Review: Scope

### ISSUE THREAD

**Issue by Edwardhyw** [brandonduong/Farming-Matters#26]
In the scope section, the document included the physical setup as part of the hazard analysis, however, there lacks a full analysis on the hazard associated with the physical setup.  Component such as keyboard, mouse which was included in the scope was not documented in the FMEA table. If those component are out of the scope of the document, it should be stated.

**Comment by brandonduong** [comment]
Thanks, we have made it more clear in the scope that the physical setup is not included
