### ISSUE TITLE
Team 10 Review: Software Validation Plan

### ISSUE THREAD

**Issue by michaela-schnull** [brandonduong/Farming-Matters#32]
The software validation plan section mentions that data from the professor's survey will be used to validate the game. Could you be more specific as to how this data can be used to validate your software? Also, if the purpose of this software is to improve the data compared to data obtained from surveys, is this sufficient to validate the system?

**Comment by AndrewBal802** [comment]
Thank you for the issue, we have removed the content concerned with the previous data being used as it would not be as helpful as we initially thought.
