### ISSUE TITLE
Team 10 Review: Test Case IR1

### ISSUE THREAD

**Issue by michaela-schnull** [brandonduong/Farming-Matters#35]
How is the API response time going to be measured? Also, the symbolic parameter API_RESPONSE_TIME does not appear in the appendix.

**Comment by namit-c** [comment]
Initially we were planning on having endpoints, other than just the databases, and were going to measure times on those. This is no longer the approach as most of the functionality is in the front end, excluding the database. Therefore, this test is no longer required and will be removed from the test plan.
