### ISSUE TITLE
Team 09 Review: SystDes should contain information on your firmware stack.

### ISSUE THREAD

**Issue by amosyu2000** [brandonduong/Farming-Matters#50]
You did a great job specifying the software stack (what technologies/language you are using) on the development side! However, I think it would be beneficial to also include information on the firmware stack on the user side.

- Since the frontend is in React, will this project be used in the browser or through a computer application? 
- If it used in a browser, which browsers are compatible, and which are not compatible?
- If it used directly through a computer application, does the computer need any technologies pre-installed (ex. node, firebase)? Or will it be an .exe file?
- Which operating systems (Mac, Windows, Linux) will be compatible?

@NickCapstone

**Comment by brandonduong** [comment]
thanks, specified that project will be accessed by browser
