### ISSUE TITLE
Team 09 Review: MIS/MG Reflection Appendix

### ISSUE THREAD

**Issue by aaronhsli** [brandonduong/Farming-Matters#51]
Great job on the MIS! I think it's very detailed and well thought-out. One thing that I noticed was that the Appendix in the MIS was missing some information about the limitations of your proposed solution and didn't offer other solutions (or paths) that could be used to solve the problem. 

![image](https://user-images.githubusercontent.com/58313755/213884079-b338b70c-1803-433d-bba7-b89a616f5ea0.png)

**Comment by aaronhsli** [comment]
@nickcapstone

**Comment by brandonduong** [comment]
thanks, added to SystDes
