### ISSUE TITLE
Team 09 Review: SystDes Timeline should contain some testing information

### ISSUE THREAD

**Issue by MannyLemos** [brandonduong/Farming-Matters#52]
The timeline is very well laid out and includes great detail. However, the rubric states

Full testing/verification does not have to be part of the timeline, but enough testing has to be included to have confidence in Rev 0.

Thus, I think some testing detail should be included in the timeline.

@NickCapstone

**Comment by brandonduong** [comment]
Added dates for testing for rev 0
