### ISSUE TITLE
Review-VnVReport-Team8: Verification of Documents

### ISSUE THREAD

**Issue by Yichen226** [brandonduong/Farming-Matters#77]
There are some testings (like in function requirements - account testing) failed because the features haven’t been implemented. Is that feature removed from the product? Or is the feature gonna be implemented later? Is there any corresponding change in the former documents(SRS, Design Doc, VnV plan)? We would expect some verification on documents in the VnV report.

**Comment by AndrewBal802** [comment]
Addressed, thank you. We have made multiple changes since then and now have passed test cases.
