### ISSUE TITLE
Review-VnVReport-Team8: Consistency

### ISSUE THREAD

**Issue by Yichen226** [brandonduong/Farming-Matters#78]
The format and tense of the testings through entire document should be consistent. For instance, the expected result could be all expressed in present tense or all use the verb **should**. It helps the overall consistency of the document. 

Example:
Test-GM16 expected result: The user balance increased by $150 and their balance is now $1150
Test-GM6 expected result: The consultant prompt should automatically happen to purchase for a consultants advice or not

Besides, some of the testings are labelled with type, while the others are not.

**Comment by harunm1** [comment]
Issue has been addressed.
