### ISSUE TITLE
Review-VnVReport-Team8: Module and Code Coverage

### ISSUE THREAD

**Issue by Yichen226** [brandonduong/Farming-Matters#79]
In **Tabel 10: Trace Between Tests and Modules**, some modules are not covered (like M9). Is it because this module is removed from the project? There could be clear explanations about that. Also, for 71.42% coverage of code of core functions and 33.33% coverage of code of accounts and authentication, there could also be explanations or discussions.

**Comment by harunm1** [comment]
This has been addressed. There was a poor function coverage that was revealed in our automated testing because the team had prioritized testing more modules more thoroughly than other because some modules were much more significant in gather research than the others.
